[tool.poetry]
name = "t_renovate"
version = "0.1.0"
package-mode = false
packages = [
    { include = "src"}
]

[tool.poetry.dependencies]
python = "^3.12"
pydantic = "==2.10.1"
pytest = "==9.0.2"
test-sublibrary = { git = "git@github.com:yuliabarabash2601/test_sublibrary.git", tag = "v1.0.0" }



[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
